$ mkdir project
$ touch dim_policy.sql dim_product.sql


#This code is in dim_policy.sql
$ vi dim_policy.sql
use dbo;
select 'POLICY_ID' , 'VALID_FROMDATE' , 'VALID_TODATE' , 'RECORD_VERSION' , 'POL_POLICYNUMBERPREFIX' , 'POL_POLICYNUMBER' , 'POL_POLICYNUMBERSUFFIX' , 'POL_ORIGINALEFFECTIVEDATE' , 'POL_QUOTEDDATE' , 'POL_ISSUEDDATE' , 'POL_BINDERISSUEDDATE' , 'POL_ASL' , 'POL_MASTERSTATE' , 'POL_MASTERCOUNTRY' , 'POL_CONVERSIONINDCODE' , 'POL_ACCOUNT' , 'POL_ACCOUNTDESCRIPTION' , 'POL_AUTOMATEDAPPROVALPOLICY' , 'POL_GENERATIONSOURCE' , 'POL_UNIQUEID', 'SOURCE_SYSTEM' , 'LOADDATE'
union
SELECT POLICY_ID,VALID_FROMDATE,VALID_TODATE,RECORD_VERSION,POL_POLICYNUMBERPREFIX,POL_POLICYNUMBER,POL_POLICYNUMBERSUFFIX,POL_ORIGINALEFFECTIVEDATE,POL_QUOTEDDATE,POL_ISSUEDDATE,POL_BINDERISSUEDDATE,POL_ASL,POL_MASTERSTATE,POL_MASTERCOUNTRY,POL_CONVERSIONINDCODE,POL_ACCOUNT,POL_ACCOUNTDESCRIPTION,POL_AUTOMATEDAPPROVALPOLICY,POL_GENERATIONSOURCE,POL_UNIQUEID,SOURCE_SYSTEM, LOADDATE from dim_policy into OUTFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/dim_policy_with_header.csv' FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\r\n';

#This code is in dim_product.sql
$vi dim_product.sql
use dbo;select 'PRODUCT_ID','PRODUCT_UNIQUEID', 'PRDT_GROUP','PRDT_NAME','PRDT_LOB','PRDT_DESCRIPTION','SOURCE_SYSTEM','LOADDATE'
union
SELECT * from dim_product INTO OUTFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/dim_product_with_headers.csv'
       FIELDS TERMINATED BY '|'
       OPTIONALLY ENCLOSED BY '"'
       LINES TERMINATED BY '\r\n';
       

       
